    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_USER: me
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: data
        volumes: 
        - ./mysql:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        links:
            - db
        ports:
            - "8080:8080"
    apache:
        image: webdevops/php-apache-dev
        restart: always
        ports:
            - "80:80"
            - "443:443"
        links:
            - db
